### ISSUE TITLE
Some issues for wslu part

### ISSUE THREAD

**Issue by patrick330602** [sirredbeard/WLinux#2]
Hi, I am the author for wslu, and thank you for including my project!

But there is some small issues I found:

This line seems to be a typo: https://github.com/sirredbeard/WLinux/blob/13daf321fde605ab09098ff172a9f67a4bdea1b6/create-targz.sh#L25

Also, I find that the installation script is wrong, you should use the following instead:

```bash
sudo apt install lsb-release apt-transport-https
wget -O - https://api.patrickwu.ml/public.key | sudo apt-key add -
echo "deb https://apt.patrickwu.ml/ `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list 
sudo apt update
sudo apt install wslu
```

**Comment by sirredbeard** [comment]
I fixed the wslu install script. The use of >> instead of tee was a hold over from when I was trying to include wslu in the original image, which as I mentioned in the other issue caused headaches.

I also had fixed the other typos, pushed those edits.

I would like to revisit including wslu by default in the future, the key handling was wonky in the chroot image build environment.
